spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/refresh_token_db
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
      encoding: UTF-8
jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: 900000 # 1000 * 60 * 15 (15min)
    refresh: 1209600000 # 1000 * 60 * 60 * 24 * 14 (14days)
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: selfsigned
    enabled: true